### ISSUE TITLE
Can this work with transposed convolutions?

### ISSUE THREAD

**Issue by nitschw** [basveeling/keras-gcnn#1]
Not really an issue, more of a question. 

I have a semantic segmentation network that I designed. It uses convolutional layers, pooling layers, and transposed convolutions to upsample. I notice you have implementations of gcnn for pooling and convolutional layers but was wondering your layers are mathematically compatible with the built in keras transposed convolutions (upsample2d)

**Comment by basveeling** [comment]
They should be, but not sure if the implementation is trivial. @nom should have more info on this.

**Comment by basveeling** [comment]
Done, thanks @nom!

**Comment by charleswg** [comment]
Anyone have experience that model with GConv2D transpose cannot be loaded after saving?  It's complaining array size when loading model config. GConv2D doesn't have the same issue.

@basveeling 
@nom

**Comment by nom** [comment]
@charleswg Haven't had issues with that myself. Could you provide a simple code example that reproduces the error?

**Comment by charleswg** [comment]
@nom Glad that isn't an issue for you. In that case, maybe it's version compatibility issue. I saw a previous commit regarding _keras_shape, which is still working in my script. I'd try to revert it and see if it helps.
- didn't work. Here's a sample code:



```python
import os 
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import numpy as np
import glob
from joblib import Parallel, delayed
import multiprocessing
import nibabel as nib
from sklearn.model_selection import train_test_split
from keras.models import *
from keras.initializers import *
from keras.layers import Input, merge, Conv2D, MaxPooling2D, UpSampling2D, Dropout, Cropping2D, BatchNormalization, Activation, concatenate, Add
from keras.optimizers import *
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, EarlyStopping, ReduceLROnPlateau, TensorBoard
from keras import backend as keras
import matplotlib.pyplot as plt
import pickle
from scipy import ndimage

import tensorflow
print(tensorflow.__version__)
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import keras.backend as K
from keras.applications.imagenet_utils import _obtain_input_shape
from keras.applications.imagenet_utils import preprocess_input as _preprocess_input
from keras.engine.topology import get_source_inputs
from keras.layers import Activation
from keras.layers import AveragePooling2D
from keras.layers import BatchNormalization
from keras.layers import Conv2D
from keras.layers import Conv2DTranspose
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import GlobalAveragePooling2D
from keras.layers import GlobalMaxPooling2D
from keras.layers import Input
from keras.layers import MaxPooling2D
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import concatenate
from keras.models import Model
from keras.regularizers import l2

from keras_gcnn.layers import GConv2D, GBatchNorm
from keras_gcnn.layers.pooling import GroupPool


```

    Using TensorFlow backend.


    1.3.0
    [name: "/cpu:0"
    device_type: "CPU"
    memory_limit: 268435456
    locality {
    }
    incarnation: 13234578321893044243
    , name: "/gpu:0"
    device_type: "GPU"
    memory_limit: 11324823962
    locality {
      bus_id: 1
    }
    incarnation: 1991661840578309748
    physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0"
    ]



```python
from keras.losses import binary_crossentropy
import keras.backend as K


def w_dice_coeff(y_true, y_pred):
    weight=0.25
    smooth = 1
    w, m1, m2 = weight * weight, y_true, y_pred
    intersection = (m1 * m2)
    score = (2. * K.sum(w * intersection) + smooth) / (K.sum(w * m1) + K.sum(w * m2) + smooth)
    return score


def weighted_dice_coeff(y_true, y_pred, weight):
    smooth = 1.
    w, m1, m2 = weight * weight, y_true, y_pred
    intersection = (m1 * m2)
    score = (2. * K.sum(w * intersection) + smooth) / (K.sum(w * m1) + K.sum(w * m2) + smooth)
    return score

def weighted_dice_loss(y_true, y_pred):
    y_true = K.cast(y_true, 'float32')
    y_pred = K.cast(y_pred, 'float32')
    # if we want to get same size of output, kernel size must be odd number
    if K.int_shape(y_pred)[1] == 128:
        kernel_size = 11
    elif K.int_shape(y_pred)[1] == 256:
        kernel_size = 21
    elif K.int_shape(y_pred)[1] == 512:
        kernel_size = 21
    elif K.int_shape(y_pred)[1] == 1024:
        kernel_size = 41
    else:
        raise ValueError('Unexpected image size')
    averaged_mask = K.pool2d(
        y_true, pool_size=(kernel_size, kernel_size), strides=(1, 1), padding='same', pool_mode='avg')
    border = K.cast(K.greater(averaged_mask, 0.005), 'float32') * K.cast(K.less(averaged_mask, 0.995), 'float32')
    weight = K.ones_like(averaged_mask)
    w0 = K.sum(weight)
    weight += border * 2
    w1 = K.sum(weight)
    weight *= (w0 / w1)
    loss = 1 - weighted_dice_coeff(y_true, y_pred, weight)
    return loss


class myUnet_gconv_Transpose(object):

    def __init__(self, img_rows = 512, img_cols = 512, lr=1e-2,batch=1,epoch=10,num_classes=1,channels=3, features=16, use_gcnn=None, conv_group=None, depth_multiplier=1):

        self.img_rows = img_rows
        self.img_cols = img_cols
        self.lr = lr
        self.batch=batch
        self.epoch=epoch
        self.num_classes=num_classes
        self.channels=channels
        self.features=features
        self.use_gcnn=use_gcnn
        self.conv_group=conv_group
        self.depth_multiplier=depth_multiplier

    def get_unet_256_vf(self):
        num_classes=self.num_classes
        channels=self.channels
        conv_group=self.conv_group
        inputs = Input((self.img_rows, self.img_cols,channels))
        f = self.features
        
        down0 = GConv2D(f, (3, 3), padding='same',kernel_initializer = 'he_normal',h_input='Z2',h_output=conv_group,bias_initializer=Constant(0.0001))(inputs)
        down0 = GBatchNorm(conv_group)(down0)
        down0 = Activation('relu')(down0)
#         down0 = Dropout(0.2)(down0)
        down0 = GConv2D(f, (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(down0)
        down0 = GBatchNorm(conv_group)(down0)
        down0 = Activation('relu')(down0)
        down0_pool = MaxPooling2D((2, 2), strides=(2, 2))(down0)
        
        down1 = GConv2D(int(2*f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(down0_pool)
        down1 = GBatchNorm(conv_group)(down1)
        down1 = Activation('relu')(down1)
#         down1 = Dropout(0.2)(down1)
        down1 = GConv2D(int(2*f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(down1)
        down1 = GBatchNorm(conv_group)(down1)
        down1 = Activation('relu')(down1)
        down1_pool = MaxPooling2D((2, 2), strides=(2, 2))(down1)        
        
        center = GConv2D(int(4*f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(down1_pool)
        center = GBatchNorm(conv_group)(center)
        center = Activation('relu')(center)
        center = GConv2D(int(4*f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(center)
        center = GBatchNorm(conv_group)(center)
        center = Activation('relu',name='center')(center)

#         up1 = UpSampling2D((2, 2))(center)
        print("before GConv2D Tranpose shape:",center._keras_shape)
        up1 = GConv2D(int(4*f), (3, 3), transpose=True, strides=2, padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(center)
        print("after GConv2D Transpose shape:", up1._keras_shape)
        print("concatenate two inputs with shapes:", down1._keras_shape, up1._keras_shape)
        up1 = concatenate([down1, up1], axis=3)
        print("after concatenate shape:", up1._keras_shape)
        up1 = GConv2D(int(2*f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(up1)
        up1 = GBatchNorm(conv_group)(up1)
        up1 = Activation('relu')(up1)
        up1 = GConv2D(int(2*f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(up1)
        up1 = GBatchNorm(conv_group)(up1)
        up1 = Activation('relu')(up1)

#         up0 = UpSampling2D((2, 2))(up1)
        up0 = GConv2D(int(2*f), (3, 3), transpose=True, strides=2, padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(up1)
        up0 = concatenate([down0, up0], axis=3)
        up0 = GConv2D(int(f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(up0)
        up0 = GBatchNorm(conv_group)(up0)
        up0 = Activation('relu')(up0)
        up0 = GConv2D(int(f), (3, 3), padding='same',kernel_initializer = 'he_normal',h_input=conv_group,h_output=conv_group,bias_initializer=Constant(0.0001))(up0)
        up0 = GBatchNorm(conv_group)(up0)
        up0 = Activation('relu')(up0)

        up0 = GroupPool(h_input=conv_group)(up0)

        classify = Conv2D(num_classes, (1, 1), activation='sigmoid')(up0)
        
        model = Model(inputs=inputs, outputs=classify)

        model.compile(optimizer = Adam(lr=self.lr), loss = weighted_dice_loss, metrics = [w_dice_coeff])

        return model
    

```


```python
myunet = myUnet_gconv_Transpose(lr=3e-4,batch=1,epoch=1,img_rows=256, img_cols=256, channels=2, num_classes=1, features=4,conv_group='D4')
model = myunet.get_unet_256_vf()
# model.summary()
print("Initialize unet")

train_imgs=np.random.randint(5, size=(100, 256,256,2))
train_masks=np.random.randint(5, size=(100, 256,256,1))

model_checkpoint = [ModelCheckpoint('unet.hdf5', monitor='val_loss',verbose=1, save_best_only=True)]

validation_split=0.2
history=model.fit(train_imgs[...], train_masks[...], batch_size=1, epochs=1,verbose=0,validation_split=0.2, shuffle=True,callbacks=model_checkpoint)

```

    before GConv2D Tranpose shape: (None, 64, 64, 128)
    after GConv2D Transpose shape: (None, 128, 128, 128)
    concatenate two inputs with shapes: (None, 128, 128, 64) (None, 128, 128, 128)
    after concatenate shape: (None, 128, 128, 192)
    Initialize unet
    
    Epoch 00001: val_loss improved from inf to -0.06122, saving model to unet.hdf5



```python
model = load_model('unet.hdf5', custom_objects={'weighted_dice_loss': weighted_dice_loss, 'w_dice_coeff' : w_dice_coeff})
```


    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-4-132cf57bb240> in <module>()
    ----> 1 model = load_model('unet.hdf5', custom_objects={'weighted_dice_loss': weighted_dice_loss, 'w_dice_coeff' : w_dice_coeff})
    

    ~/anaconda3/lib/python3.6/site-packages/keras/models.py in load_model(filepath, custom_objects, compile)
        241             raise ValueError('No model found in config file.')
        242         model_config = json.loads(model_config.decode('utf-8'))
    --> 243         model = model_from_config(model_config, custom_objects=custom_objects)
        244 
        245         # set weights


    ~/anaconda3/lib/python3.6/site-packages/keras/models.py in model_from_config(config, custom_objects)
        315                         'Maybe you meant to use '
        316                         '`Sequential.from_config(config)`?')
    --> 317     return layer_module.deserialize(config, custom_objects=custom_objects)
        318 
        319 


    ~/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
         53                                     module_objects=globs,
         54                                     custom_objects=custom_objects,
    ---> 55                                     printable_module_name='layer')
    

    ~/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
        142                 return cls.from_config(config['config'],
        143                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
    --> 144                                                            list(custom_objects.items())))
        145             with CustomObjectScope(custom_objects):
        146                 return cls.from_config(config['config'])


    ~/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py in from_config(cls, config, custom_objects)
       2522                 if layer in unprocessed_nodes:
       2523                     for node_data in unprocessed_nodes.pop(layer):
    -> 2524                         process_node(layer, node_data)
       2525 
       2526         name = config.get('name')


    ~/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py in process_node(layer, node_data)
       2481                     layer(input_tensors[0], **kwargs)
       2482                 else:
    -> 2483                     layer(input_tensors, **kwargs)
       2484 
       2485         def process_layer(layer_data):


    ~/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
        592                     self.build(input_shapes[0])
        593                 else:
    --> 594                     self.build(input_shapes)
        595                 self.built = True
        596 


    ~/anaconda3/lib/python3.6/site-packages/keras/layers/merge.py in build(self, input_shape)
        352                              'inputs with matching shapes '
        353                              'except for the concat axis. '
    --> 354                              'Got inputs shapes: %s' % (input_shape))
        355 
        356     def _merge_function(self, inputs):


    ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 128, 64), (None, 32, 32, 128)]

**Comment by charleswg** [comment]
@nom To summarize, during model building and training, keras see GConv2D output having shape (None, 128, 128, 128).  During model loading, keras see GConv2D output having shape (None, 32, 32, 128).

**Comment by nom** [comment]
@charleswg Please provide a minimal code example.

Also consider replacing transposed convs with bilinear upsampling or nearest neighbour upsampling for better performance.

**Comment by charleswg** [comment]
Thanks @nom . Abandon transpose gconv  for now. Also I found that nearest Upsampling2D do not break p4m equivariant but bilinear does break it, and it got intensify during UNet decoder phase.

**Comment by nom** [comment]
@charleswg Bilinear upsampling is exactly equivariant.
