### ISSUE TITLE
Generalization to higher dimensions

### ISSUE THREAD

**Issue by clementpoiret** [basveeling/keras-gcnn#8]
Hi, and thanks for your work.

I've a little question : I'm interested in using gcnn on higher dimensional volumes. Do you have any idea on how to make it 4d or at least 3d? 

Thanks,
Clement.

**Comment by basveeling** [comment]
Hi Clément,

Thanks for reaching out! There does exist follow up work on extending
G-CNNs to 3D. The tricky thing is that with that extra dimension, the
number of orientations under 90 degree rotations explodes (22 orientations
if I recall correctly). This can get a bit memory intensive. Here is a
reference:

https://arxiv.org/abs/1804.04458

Good luck,

Bas

**Comment by clementpoiret** [comment]
Thanks for the paper, I'll try to implement it.
Wish you the best,
Clément.
